spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  redis:
    host: localhost
    port: 6397
jwt:
  key: codestatescodestates123123123123123123123123123
  access-token-expiration-minutes: 1
  refresh-token-expiration-minutes: 420
coolsms:
  api:
    key:
    secret:
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
##  sql:
##    init:
##      data-locations: classpath*:db/h2/data.spl
