spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pettalk-backend-db.cw2apfvbuvai.ap-northeast-2.rds.amazonaws.com:13306/pettalk
    username: admin
    password: 123456789
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6397
  security:
    oauth2:
      client:
        registration:
          kakao:
            client_id: d7277e7d8ca7f14249d159840400ce09
            client_secret: NTD6r2mzx8esgO5DFtqMBJoVZDAdKqGJ
            authorization-grant-type: authorization_code
            redirect_uri: http://localhost:8080/oauth/kakao;KAKAO_SECRET=NTD6r2mzx8esgO5DFtqMBJoVZDAdKqGJ
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  key: codestatescodestates123123123123123123123123123;
  access-token-expiration-minutes: 600
  refresh-token-expiration-minutes: 420
coolsms:
  api:
    key: NCSLTCK9OAJOTYYD
    secret: DTZTGYAIEMFL8PBL9I3FLSSBVDZ98LRS