spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  redis:
    host: localhost
    port: 6397
jwt:
  key: codestatescodestates123123123123123123123123123
  access-token-expiration-minutes: 1
  refresh-token-expiration-minutes: 420
mail:
  address:
    admin: admin@gmail.com
coolsms:
  api:
    key:
    secret: